### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by dididy** [side-pool/frontend#156]
# [사이드풀 🏄‍♂️](http://118.67.154.143/)

> 사이드 프로젝트를 위한 사이드 프로젝트

<br/>
<br/>
<div align=center>
  <a href="http://118.67.154.143/side">
    <img width="960" alt="Logo" src="https://user-images.githubusercontent.com/16266103/143790014-e8c444ca-e1ae-4f42-bc7c-89f9c0c41450.png">
    <img width="960" alt="개발배경1" src="https://user-images.githubusercontent.com/16266103/143790190-6032041f-950f-4cb8-b1b1-dd4eab008d9e.png">
    <img width="960" alt="개발배경2" src="https://user-images.githubusercontent.com/16266103/143802667-0406fb45-70d9-4171-b72e-dda71e0f1b9e.png">
  </a>
</div>

## 기술스택
<div align=center>
  <img width="960" alt="기술스택" src="https://user-images.githubusercontent.com/16266103/143790311-77a56881-148c-4f9e-a7f5-203c257e39f5.png">
</div>

## 아키텍쳐 및 서비스 흐름도

<div align=center>
  <img width="960" alt="회원가입 흐름도" src="https://user-images.githubusercontent.com/16266103/143790941-7edf970a-7412-4fd6-ae8a-34b08f7bcad2.png">
</div>

<details>
  <summary>더보기</summary>

### 신규회원 회원 가입 & 회원 로그인시 사용자 흐름도
<div align=center>
  <img width="620" alt="회원가입 흐름도" src="https://user-images.githubusercontent.com/16266103/143790705-65534ba9-8f04-4157-a915-99e2b39b17ff.png">
</div>
<br/>

### JWT 토큰을 이용한 사용자 인증 구조도
<div align=center>
  <img width="620" alt="JWT Token Auth" src="https://user-images.githubusercontent.com/16266103/143790681-b14ceb9b-1611-4872-9342-86da213a7e7a.png">
</div>
<br/>

### React Query를 사용한 API 요청 핸들링 및 캐싱 처리 흐름도
<div align=center>
  <img width="620" alt="React Query" src="https://user-images.githubusercontent.com/16266103/143790710-79ac2fa2-9185-4cbd-a41d-c95fe4c730bf.png">
</div>
<br/>

### GitHub OpenAPI를 연동한 사이드 프로젝트 정보 조회 구조도
<div align=center>
  <img width="960" alt="GitHub Open API" src="https://user-images.githubusercontent.com/16266103/143790708-eaf4067e-fa3b-421b-9caf-65e4ed2fb9c5.png">
</div>

</details>

### 아이디어

![아이디어 생성](https://user-images.githubusercontent.com/16266103/143791240-15553713-414e-4daa-80bc-950325722a82.gif)

> 아이디어 생성 - 불편함을 아이디어로!

![해시태그](https://user-images.githubusercontent.com/16266103/143791233-ca8f6dfd-2201-4107-84a4-abd0b641d405.gif)

> 아이디어 해시태그 

![비슷한 서비스가 있어요](https://user-images.githubusercontent.com/16266103/143791198-6fee3590-9833-4873-85dd-486ab3f6361c.gif)

> 비슷한 서비스가 있어요 - 제안해요 => 해결되었어요!

### 사이드

![사이드_스크롤_이모지](https://user-images.githubusercontent.com/16266103/143790993-219cfa5c-6abe-462b-afe0-010c233c7717.gif)

> 사이드프로젝트를 홍보할 수 있는 공간 - 이모지로 활성화 정도 시각화

![사이드_생성](https://user-images.githubusercontent.com/16266103/143791031-b96c290e-a9c3-474e-bfc8-4b7a0ec32026.gif)

> 사이드 생성을 GitHub URL로 간단하게

![사이드_필터_댓글_좋아요](https://user-images.githubusercontent.com/16266103/143791064-f087974d-519f-4641-8e45-422d1153a640.gif)

> 최신순, 좋아요순 정렬, 다양한 검색 필터 제공

![댓글피드백](https://user-images.githubusercontent.com/16266103/143791292-d52441d0-21c8-43e5-8ed7-8bf818ec37bc.gif)

> 댓글 피드백 태그 제공

![마이페이지_알람_내가쓴](https://user-images.githubusercontent.com/16266103/143791331-13d312d6-49f4-43c9-bc89-8df7aa3c4390.gif)

> 마이페이지 내 정보, 알림, 내가쓴 사이드, 아이디어, 댓글

### 반응형

![반응형](https://user-images.githubusercontent.com/16266103/143791341-fb405722-cfef-4b24-a26d-6cfb5aaaa271.gif)

**Comment by seung-00** [comment]
접기로 만들어뒀어도 줄글은 좀 보기 불편하지 않을까? 내 생각에 어차피 아무도 안 읽을 거라면 없는게 나을듯!

**Comment by seung-00** [comment]
두 번째 이미지는 없어도 되지 않을까?
